"""create tables

Revision ID: 38c6670e8195
Revises: 
Create Date: 2024-02-23 20:08:18.696602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38c6670e8195'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('schedule_time', sa.Time(), nullable=True),
    sa.Column('personal_email', sa.String(), nullable=True),
    sa.Column('subscription', sa.Enum('BASIC', 'PREMIUM', 'NOT_SUBSCRIBED', name='usersubscription'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_audios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_address_to', sa.String(), nullable=True),
    sa.Column('email_limit', sa.Integer(), nullable=True),
    sa.Column('email_subject', sa.String(), nullable=True),
    sa.Column('email_text', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address_to')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_emails')
    op.drop_table('user_audios')
    op.drop_table('users')
    # ### end Alembic commands ###
