"""migration2

Revision ID: 3bf84819c34e
Revises: d029c7b65b42
Create Date: 2024-03-14 20:46:22.410089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf84819c34e'
down_revision: Union[str, None] = 'd029c7b65b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sent_audios')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_audios',
    sa.Column('sent_audio_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('email_id', sa.INTEGER(), nullable=True),
    sa.Column('audio_id', sa.INTEGER(), nullable=True),
    sa.Column('send_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['audio_files.audio_id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['user_emails.email_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('sent_audio_id')
    )
    # ### end Alembic commands ###
