"""migration2

Revision ID: 45d697bcc392
Revises: 38c6670e8195
Create Date: 2024-02-24 15:57:32.517223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d697bcc392'
down_revision: Union[str, None] = '38c6670e8195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('schedule_time', sa.Time(), nullable=True),
    sa.Column('email_text', sa.String(), nullable=True),
    sa.Column('email_subject', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user_emails', 'email_text')
    op.drop_column('user_emails', 'email_limit')
    op.drop_column('user_emails', 'email_subject')
    op.add_column('users', sa.Column('email_limit', sa.Integer(), nullable=True))
    op.drop_column('users', 'schedule_time')
    op.drop_column('users', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('quantity', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('schedule_time', sa.TIME(), nullable=True))
    op.drop_column('users', 'email_limit')
    op.add_column('user_emails', sa.Column('email_subject', sa.VARCHAR(), nullable=True))
    op.add_column('user_emails', sa.Column('email_limit', sa.INTEGER(), nullable=True))
    op.add_column('user_emails', sa.Column('email_text', sa.VARCHAR(), nullable=True))
    op.drop_table('email_settings')
    # ### end Alembic commands ###
