"""migration5

Revision ID: 83ba84f88a7a
Revises: 917f606c316d
Create Date: 2024-03-03 17:16:11.275514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ba84f88a7a'
down_revision: Union[str, None] = '917f606c316d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('real_name', sa.String(), nullable=True),
    sa.Column('admin_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_id')
    )
    op.create_table('user_emails',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.drop_table('artist_emails')
    op.drop_constraint(None, 'sent_audios', type_='foreignkey')
    op.create_foreign_key(None, 'sent_audios', 'user_emails', ['email_id'], ['email_id'])
    op.alter_column('users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_column('users', 'email')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.alter_column('users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'sent_audios', type_='foreignkey')
    op.create_foreign_key(None, 'sent_audios', 'artist_emails', ['email_id'], ['email_id'])
    op.create_table('artist_emails',
    sa.Column('email_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('email_address', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.drop_table('user_emails')
    op.drop_table('admins')
    # ### end Alembic commands ###
