"""empty message

Revision ID: 917f606c316d
Revises: 01ed22b39044
Create Date: 2024-03-03 16:34:05.763372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917f606c316d'
down_revision: Union[str, None] = '01ed22b39044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_emails',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.create_table('audio_files',
    sa.Column('audio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('audio_id')
    )
    op.create_table('sent_audios',
    sa.Column('sent_audio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('audio_id', sa.Integer(), nullable=True),
    sa.Column('send_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['audio_files.audio_id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['artist_emails.email_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('sent_audio_id')
    )
    op.drop_table('user_emails')
    op.drop_table('user_audios')
    op.add_column('email_settings', sa.Column('amount', sa.Integer(), nullable=True))
    op.add_column('email_settings', sa.Column('subject', sa.String(), nullable=True))
    op.add_column('email_settings', sa.Column('text', sa.String(), nullable=True))
    op.drop_column('email_settings', 'email_subject')
    op.drop_column('email_settings', 'quantity')
    op.drop_column('email_settings', 'email_text')
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.alter_column('users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_column('users', 'personal_email')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), nullable=False))
    op.add_column('users', sa.Column('personal_email', sa.VARCHAR(), nullable=True))
    op.alter_column('users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('users', 'email')
    op.add_column('email_settings', sa.Column('email_text', sa.VARCHAR(), nullable=True))
    op.add_column('email_settings', sa.Column('quantity', sa.INTEGER(), nullable=True))
    op.add_column('email_settings', sa.Column('email_subject', sa.VARCHAR(), nullable=True))
    op.drop_column('email_settings', 'text')
    op.drop_column('email_settings', 'subject')
    op.drop_column('email_settings', 'amount')
    op.create_table('user_audios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_id', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('size', sa.INTEGER(), nullable=True),
    sa.Column('is_sent', sa.BOOLEAN(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_emails',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email_address_to', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address_to')
    )
    op.drop_table('sent_audios')
    op.drop_table('audio_files')
    op.drop_table('artist_emails')
    # ### end Alembic commands ###
