"""Add available extra limit

Revision ID: db0a9ff347dc
Revises: 5f776c9e8850
Create Date: 2024-04-29 17:13:13.525607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db0a9ff347dc'
down_revision: Union[str, None] = '5f776c9e8850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_settings', sa.Column('email_limit_to_send_for_extra', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_settings', 'email_limit_to_send_for_extra')
    # ### end Alembic commands ###
