"""Первая миграция

Revision ID: ef801dbb0304
Revises: 
Create Date: 2024-02-17 18:38:31.128485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef801dbb0304'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('personal_email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('premium', sa.Boolean(), nullable=True),
    sa.Column('schedule_time', sa.Time(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('audio_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_address_to', sa.String(), nullable=True),
    sa.Column('email_limit', sa.Integer(), nullable=True),
    sa.Column('email_subject', sa.String(), nullable=True),
    sa.Column('email_text', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address_to')
    )
    op.drop_table('users')
    op.drop_table('emails')
    op.drop_table('audios')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audios',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('file_id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('size', sa.INTEGER(), nullable=False),
    sa.Column('is_sent', sa.TEXT(), nullable=True)
    )
    op.create_table('emails',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('email_address_to', sa.TEXT(), nullable=True),
    sa.Column('is_sent', sa.TEXT(), nullable=True)
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('personal_email', sa.TEXT(), nullable=True),
    sa.Column('password', sa.TEXT(), nullable=True),
    sa.Column('premium', sa.TEXT(), nullable=True),
    sa.Column('email_limit', sa.INTEGER(), server_default=sa.text('(50)'), nullable=True),
    sa.Column('email_header', sa.TEXT(), nullable=True),
    sa.Column('email_desc', sa.TEXT(), nullable=True),
    sa.Column('schedule_time', sa.TEXT(), nullable=True),
    sa.Column('audio_quantity', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('email_list')
    op.drop_table('audio_list')
    op.drop_table('user_info')
    # ### end Alembic commands ###
