"""secret column adding

Revision ID: fbfd5cd2d187
Revises: db0a9ff347dc
Create Date: 2024-06-09 14:45:15.084897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbfd5cd2d187'
down_revision: Union[str, None] = 'db0a9ff347dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'secret')
    # ### end Alembic commands ###
