"""Add available is for audio

Revision ID: fd6804a0a1c9
Revises: 55ad51e71d99
Create Date: 2024-04-23 16:30:19.730671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6804a0a1c9'
down_revision: Union[str, None] = '55ad51e71d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_files', sa.Column('available_is_for_audio', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_files', 'available_is_for_audio')
    # ### end Alembic commands ###
